language: generic

deploy:
  provider: firebase
  message: "Autodeploy from Travis CI."
  token:
      secure: "l4X1XxemLN36lG+8jft9TFWWPzM5PDbWZCQlEudKGwxRoHzbmqWqKg5Ns2TswjVZ0dcf4vxR3QjLCvEuj6N0q4t3tW6+8F0Ig0ZMlJ+mC9bVDofC1ZwIUfbYYi56dIESlqOm86tAwOZTXNwcoNSg2C7AaXJCSYR+6T5ObUEmY5t16mThhLlRvodfEhDbkeYKf+xA7jXjVfIbXxkj3Ps2boFXcWklnfSmhHhCqUYZ9taqYtWUSzNXtd5d2DHiZ1mAHnUYwtZ5dyhwHKO4zjh7YhqO//9lmjvA1SgUOjOIdylPSoe/23SP0I7lx0Ug43pp7MvbWZC0qTW4dsCFoxD7KEJUpMNRrv3Ge5ERmUbeqwSGdtO7BYIKXaOnJYRaHoARhkssmJ83JaDAft8DMHQqE4Tt5nBW1yrJSXpS28fhg9YY+uP5t/m9gV6W2lj736XkPHMg2mkk6Jhj+s2D1X2tQ/Wfm9w3OcxFYXnpfNc+owfaW/BwPUhk4ewaYdWEhHMa35dMmUIzlcuPxo34/hsLd0PDJmYMos7fh5bedztNASDbHlDWaAmb37eaccxqYCh10rhwDyW31zsUJz2laZXP3m0qkemIOJk98WV9d7eCHiSUvV1CRhIucPsaxy9J9kfHokvVG343mXorEsGZIAqwzZ0bfB6yLXyhmlpteE/eGj4="
